### ISSUE TITLE
Scope improvements to intake-parquet

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#1496]
As mentioned in #1564 there are a couple of features that would be nice to have in the [intake-parquet](https://github.com/intake/intake-parquet) library, that haven't yet been implemented. These include:
* `simplecache` / [fsspec](https://filesystem-spec.readthedocs.io/en/latest/) based per-file local caching (which is used in some other intake plugins). See also [this issue](https://github.com/intake/intake-parquet/issues/18).
* Ability to use [Parquet filter push down](https://drill.apache.org/docs/parquet-filter-pushdown/) to efficiently query collections of Parquet files. Currently it selects data quickly from a single file that has lots of row groups, but seems to scan all files regardless of what data they contain when data is split.
* Ability to query all parquet files in a directory (which dask and pandas are happy to do).

Contact @martindurant to get pointers on where we would want to get started, examples to reference, and potential pitfalls.

**Comment by martindurant** [comment]
Thanks for reaching out, and feel free to cross-post at intake-parquet.
I will have to check, but I would think that intake-parquet should support everything that dask's read_parquet can, including caching, filters and multifile.
For example, running the following in my local intake-parquet directory (to get the files used in testing):
```python
ds = intake.open_parquet("simplecache::file:///Users/mdurant/code/intake-parquet/tests/split/**.parquet", engine="pyarrow", storage_options={"simplecache": {"cache_storage": '/Users/mdurant/code/intake-parquet/cache'}}, filters=[["cat", "==", "fred"]])
```
or equivalent YAML entry
```yaml
sources:
  parquet:
    args:
      engine: pyarrow
      filters:
      - - cat
        - ==
        - fred
      storage_options:
        simplecache:
          cache_storage: /Users/mdurant/code/intake-parquet/cache
      urlpath: simplecache::file:///Users/mdurant/code/intake-parquet/tests/split/**.parquet
    description: ''
    driver: intake_parquet.source.ParquetSource
    metadata: {}
```
correctly populates the given cache directory and filters on the categorical.
