### ISSUE TITLE
Make workflow_dispatch trigger work for integration tests

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#3370]
When we set up the merge queue we tried to enable running the integration tests with a `workflow_dispatch` trigger so we could test the CI without needing to submit something to the queue, but this conditional doesn't seem to be working.

```yaml
  ci-integration:
    runs-on:
      group: large-runner-group
      labels: ubuntu-22.04-4core
    if: github.event.merge_group || github.event.workflow_dispatch
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0}
```
