### ISSUE TITLE
Adding Support for Native Windows (Lock Configurations)

### ISSUE THREAD

**Issue by hrishikeshh** [catalyst-cooperative/pudl#3568]
**Is your feature request related to a problem? Please describe.**
Yes. This feature request is based upon a bottle neck faced while dev environment setup by multiple windows users. 

Whenever windows users are trying to **setup their dev environment** using command `make install-pudl`, it leads to platform validation issues since `environment` configurations (`conda.yml` file) only covers locks for:-
- linux-64, 
- osx-64, 
- osx-arm64

Refer the specific configs in the `conda-lock.yml`
```yml
metadata:
  content_hash:
    linux-64: 09c78383a83af1c2bf06013b06ef870afea96baa86bd8d9373ec0d5215804c8d
    osx-64: 7e63fa499a48eca9f5a939548fc6b8f2b84d82642073a139604fe68ef780e1a2
    osx-arm64: c694e1530235797a6bda755e6e04d7577cca6ca86ca8e51f52e72f6c85b73f8a
  channels:
    - url: conda-forge
      used_env_vars: []
    - url: defaults
      used_env_vars: []
  platforms:
    - linux-64
    - osx-64
    - osx-arm64
  sources:
    - ../pyproject.toml
```
This results into `PlatformValidationError`. 

There is no directly available solution for native window systems using `powershell` or `cmd`

**Describe the solution you'd like**

Support for `windows` (`win64`) should be directly added in the `environment`. A section in `conda-lock.yml` or a seperate config for `win64` should be there if technically feasible.  

**Describe alternatives you've considered**
- Currently to bypass this, users have to use either Windows Subsystem for Linux `wsl` or Linux `Ubuntu`. 
- Alternatively, can add the following suitable arguments to the conda-lock command:
`--platform=win-64` 
`--platform=linux-64`
`--platform=osx-64`
` --platform=osx-arm64`
