### ISSUE TITLE
Migrate vs_bounds tests to dbt

### ISSUE THREAD

**Issue by zaneselvans** [catalyst-cooperative/pudl#4106]
Many tests use the method `vs_bounds` defined in `validate.py`. These tests compute a quantile (either weighted or standard) and compare the value to some configurable bounds. These tests can be migrated into the new framework using the `dbt_helper` script.

However, it's unclear how valuable or valid the unweighted quantile checks that are being applied to the FERC tables are. Conceptually, these should be weighted just like the other validation tests. Why aren't they?

- @marianneke has updated the SQL based weighted quantile calculation to be continuous in #4090. 
- However there are some tests that got migrated and made more lax using the discrete distribution, which need to be reverted.
- The rest of the weighted quantile tests should be migratable using the new continuous distribution macro.

**Comment by zaneselvans** [comment]
@marianneke I linked this to #4090 but if you want to do the SQL calculation and validation test migrations separately you'll want to keep this open after that PR merges / attach it to the new PR.

**Comment by krivard** [comment]
What is left to do on this?

**Comment by zaneselvans** [comment]
It looks like there are a number of `vs_bounds` calls still peppered throughout the `test/validate/*.py` modules -- maybe verify which ones have been migrated to `dbt` and delete those modules / test calls as you go... and if at the end there are none left, delete the function definition and any mentions of it that show up elsewhere?

**Comment by krivard** [comment]
Okay, so for each of the *thirty-two* `vs_bounds` tests, we need to:
- [ ] open the original test location in pythonland
- [ ] open the corresponding schema.yml
- [ ] eyeball-compare the values to make sure they match, and fix values / add tests as needed
- [ ] delete the pythonland test

And then finally delete the central `vs_bounds` python definition. Yes?

**Comment by krivard** [comment]
I have compiled [a full list of all the table/test-config pairs](https://docs.google.com/spreadsheets/d/14N7C31d9SKzAf6BpwE9nYhpePiwI_JR1Bfwi34xH-Jg/edit?gid=1777256416#gid=1777256416) and there are just over one hundred of them, which is beyond my tolerance for a manual process with this many steps.

I propose a script which does the following:
* for each table,
  * load the schema.yml
  * drop all existing expect_column_weighted_quantile_values_to_be_between entries
  * drop all existing dbt_expectations.expect_column_quantile_values_to_be_between entries
  * save the schema.yml
  * for each test config for that table,
    * run `dbt_helper migrate-tests`
  * run prettier
  * commit the change

This will still have a massive review impact, but I'm not sure what we can really do about that. Maybe have a human do the actual commit for each table, as a first-pass safety check? There are only 12 tables, so maybe. 

We would still need to go into each original test location to delete it. If we're pausing at the end of each table anyway to let a human look over the proposed commit, maybe the script can open those files automatically.

This will be miserable if any of the below are true:
* There are any manually-added expect_*quantile_values_to_be_between entries which were not listed in the spreadsheet
* There are more than ~8 entries in any particular schema.yml file, and they end up inserted in a different order than they were before

We could instead write a script that automatically checks if the existing values match the ones in validate.py, but that would take longer to write and test than just blowing away what's already there and reverting to the already-tested migration script. It would give us a chance to skip any nonmatching checks which were added manually, but the logic for that could be squirrelly.

**Comment by krivard** [comment]
> However there are some tests that got migrated and made more lax using the discrete distribution, which need to be reverted.

ahh, much of the horror in the above was because I figured "some" was significant -- there are only 3 tables with existing checks that need to be cleared, reverted, or updated. That makes this much more straightforward!

**Comment by zaneselvans** [comment]
Grepping through the `dbt` folder a bit it looks like almost none of these tests have been migrated. It's only showing up in the initial examples:

```
output/out_eia__monthly_generators/schema.yml
output/out_eia__yearly_generators/schema.yml
```

And those guys don't look like they have any other manual tests added to them, so we can probably just blow them away and start from scratch if we want to and migrate everything over with the script.

There's something that would be nice to fix about how the test is specified  or how the script works before we do that though.

There are 2 ways in which this test is used:
- to check that some central tendency / peak is between two specified values (e.g. checking that the weighted median, aka quantile 0.5, is between 150 and 250).
- to check that the tails of the distribution aren't more extreme than expected.

The test is currently named `expect_column_weighted_quantile_values_to_be_between` which makes a lot of sense for the first type of check.  However, the way they're currently migrated now... it creates two separate test instances.  One with a max value and one with a min value, attached to the same quantile and selection criteria. This is kinda unintuitive and not really in line with the name of the test. And also seems like it'll probably result in more computation than necessary (and I think with all the weighted quantile calculations, this is probably our most computationally intensive test)

If possible it would be nice to pull those checks into a single test with  both a min and a max.  E.g. this:

```yaml
              - expect_column_weighted_quantile_values_to_be_between:
                  quantile: 0.65
                  min_value: 0.4
                  row_condition: fuel_type_code_pudl='gas' and report_date>=CAST('2015-01-01' AS DATE) and capacity_factor<>0.0
                  weight_column: capacity_mw
              - expect_column_weighted_quantile_values_to_be_between:
                  quantile: 0.65
                  max_value: 0.7
                  row_condition: fuel_type_code_pudl='gas' and report_date>=CAST('2015-01-01' AS DATE) and capacity_factor<>0.0
                  weight_column: capacity_mw

```
would become this
```yaml
              - expect_column_weighted_quantile_values_to_be_between:
                  quantile: 0.65
                  min_value: 0.4
                  max_value: 0.7
                  row_condition: fuel_type_code_pudl='gas' and report_date>=CAST('2015-01-01' AS DATE) and capacity_factor<>0.0
                  weight_column: capacity_mw
```

Is there any analogous way to make the tails tests below more intuitive? How can this be made more readable? We could include `max_value: Inf` and `min_value: -Inf` or something to make the lack of upper/lower boundaries explicit.

Given that all 4 of these tests are using the same selection criteria and working on the same weighted cumulative distribution, is there any easy way to use the same query to run all of the tests and specify it all in a single compact check?  It seems like that would also reduce the changes of someone accidentally updating the selection criteria for one but not all of the related checks.

```yaml
              - expect_column_weighted_quantile_values_to_be_between:
                  quantile: 0.15
                  min_value: 0.005
                  row_condition: fuel_type_code_pudl='gas' and report_date>=CAST('2015-01-01' AS DATE) and capacity_factor<>0.0
                  weight_column: capacity_mw
              - expect_column_weighted_quantile_values_to_be_between:
                  quantile: 0.95
                  max_value: 0.95
                  row_condition: fuel_type_code_pudl='gas' and report_date>=CAST('2015-01-01' AS DATE) and capacity_factor<>0.0
                  weight_column: capacity_mw
```

**Comment by krivard** [comment]
Okay, I have a macro that will accept input that looks like this:

```
              - expect_quantile_constraints:
                  row_condition: fuel_type_code_pudl='gas' and report_date>=CAST('2015-01-01' AS DATE) and capacity_factor<>0.0
                  weight_column: capacity_mw
                  constraints:
                    - quantile: 0.65
                      min_value: 0.4
                      max_value: 0.7
                    - quantile: 0.15
                      min_value: 0.005
                    - quantile: 0.95
                      max_value: 0.95
```

There is one downside: we can't limit severity on a subset of the constraints; it's all or nothing.

I did manage to augment the output so if it fails, you can at least see which quantile had the failure, though I couldn't figure out how to dig out the actual value that failed. So you get this:

```
$ duckdb $PUDL_OUTPUT/pudl.duckdb 
v1.2.0 5f5512b827
Enter ".help" for usage hints.
D .read target/compiled/pudl_dbt/models/output/out_eia__monthly_generators/schema.yml/source_expect_quantile_constra_2210e57c6b5f0685d5604bfb48af46cb.sql
┌──────────┬────────────┐
│ quantile │ expression │
│ varchar  │  boolean   │
├──────────┼────────────┤
│ 0.65     │ false      │
│ 0.65     │ false      │
│ 0.65     │ false      │
│ 0.65     │ false      │
│ 0.65     │ false      │
│ 0.65     │ false      │
[...]
```

Good enough and go ahead with collapsing all quantile checks to a single entry?

Or, keep the severity flexibility, and accept three entries (a one-sided entry for the bottom tail, a two-sided entry for the median, and a one-sided entry for the top tail)?
