### ISSUE TITLE
Dagster says my asset is "queued" and never materializes it.

### ISSUE THREAD

**Issue by krivard** [catalyst-cooperative/pudl#4343]
When I click "Materialize all" or "Materialize" in the Dagster UI, it says the asset is "queued". In the asset graph it shows the assets as "Materializing...". When I view the run details, it says

```
Run queued
This run is queued for execution and will start soon.
```

...but it never actually does anything. 

If I view the config at http://localhost:3000/deployment/config I get:

```
local_artifact_storage:
  module: dagster._core.storage.root
  class: LocalArtifactStorage
  config:
    base_dir: [path redacted but it's $DAGSTER_HOME]
run_storage: SqliteRunStorage
event_log_storage: SqliteEventLogStorage
compute_logs: NoneType
schedule_storage: SqliteScheduleStorage
scheduler:
  module: dagster._core.scheduler
  class: DagsterDaemonScheduler
  config: {}
run_coordinator:
  module: dagster._core.run_coordinator
  class: QueuedRunCoordinator
  config: {}
run_launcher:
  module: dagster
  class: DefaultRunLauncher
  config: {}
```

How do I tell Dagster to actually execute the queued run?
